### ISSUE TITLE
Items using On Use Macro targeting Self throws an error

### ISSUE THREAD

**Issue by tposney** [tposney/midi-qol#498]
In GitLab by @diannetea on Aug 22, 2021, 03:50

Using any macro in the On Use Macro input bar (both ItemMacro or any created macro does this) throws this error in console only (as far as I can tell) when the item is targeting Self:

<details><summary>Error</summary>

```
workflow.js:810 Uncaught (in promise) TypeError: Cannot read property 'uuid' of undefined
    at Workflow.callMacros (workflow.js:810)
    at Workflow._next (workflow.js:468)
    at async Workflow.next (workflow.js:185)
	callMacros						@ workflow.js:810
	_next							@ workflow.js:468
	async function (async)
	next							@ workflow.js:185
	doDamageRoll						@ itemhandling.js:253
	async function (async)
	doDamageRoll						@ itemhandling.js:162
	🎁call_wrapper						@ libWrapper-wrapper.js:574
	🎁CONFIG.Item.documentClass.prototype.rollDamage#0 	@ libWrapper-wrapper.js:162
	_next							@ workflow.js:348
	next							@ workflow.js:185
	_next							@ workflow.js:257
	next							@ workflow.js:185
	_next							@ workflow.js:250
	next							@ workflow.js:185
	_next							@ workflow.js:247
	next							@ workflow.js:185
	_next							@ workflow.js:211
	next							@ workflow.js:185
	processItemCardCreation					@ chatMesssageHandling.js:539
	(anonymous)						@ Hooks.js:189
	_call							@ VM3019:4
	callAll							@ foundry.js:153
	callback						@ foundry.js:8777
	(anonymous)						@ foundry.js:8716
	_handleCreateDocuments					@ foundry.js:8716
	_createDocuments					@ foundry.js:8612
	async function (async)
	_createDocuments					@ foundry.js:8603
	create							@ backend.mjs:96
	async function (async)
	create							@ backend.mjs:93
	createDocuments						@ document.mjs:332
	create							@ document.mjs:431
	showItemCard						@ itemhandling.js:545
	async function (async)
	showItemCard						@ itemhandling.js:507
	doItemRoll						@ itemhandling.js:396
	async function (async)
	doItemRoll						@ itemhandling.js:266
	🎁call_wrapper						@ libWrapper-wrapper.js:574
	🎁CONFIG.Item.documentClass.prototype.roll#0 		@ libWrapper-wrapper.js:162
	_onItemRoll						@ base.js:865
	(anonymous)						@ base.js:591
	dispatch						@ jquery.min.js:2
	v.handle						@ jquery.min.js:2
```
</details>

Here are the Midi-QOL settings (though I think default with just On Use enabled breaks as well):  [fvtt-midi-qol-settings.json](https://my-gitlab-bucket.s3.amazonaws.com/640711674/9d5000c31af04e3cc19a30d470a6a7126c6c78fe084925bd0245ff7ffb1c9de6/fvtt-midi-qol-settings.json)

Here is the exported item:  [fvtt-Item-test.json](https://my-gitlab-bucket.s3.amazonaws.com/640711674/8310dd25e66c84b0e13e8c6820173d6e43e7c8eb05e61048e541deed77a6e8cd/fvtt-Item-test.json)

<details><summary>Versions and Modules</summary>

```
  Foundry: 0.8.9
  System: dnd5e version 1.4.2

Active_Modules:
  about-time: About Time v1.0.4
  dae: Dynamic effects using Active Effects v0.8.44
  foundryvtt-simple-calendar: Simple Calendar vv1.3.28
  itemacro: Item Macro v1.5.5
  lib-wrapper: libWrapper v1.8.0.0
  midi-qol: Midi QOL v0.8.45
  socketlib: socketlib v1.0.8
  tidy-ui_game-settings: Tidy UI - Game Settings v0.1.24
  times-up: times-up v0.8.12
```

</details>
